### ISSUE TITLE
[Bug]: MC 1.19.3 Forge 44.1.4 empty catalog when starting a rocket

### ISSUE THREAD

**Issue by SubSonicEr** [terrarium-earth/Ad-Astra#135]
### Bug Description

Hey there,

I'm playing MC 1.19.3 with Forge 44.1.4. I'm testing the funcitonality of Ad Adstra in creative. I'm using a lot of mods. When I'm launching the rocket, the catalog to choose a destination is empty. If you need my used mods just tell me.

Additional Info: Tested again a launch and clicked on a orange rectangle in the catalog. There was a click sound but nothing else. But for now the test map is broken stucking forever in this catalog screen you can never close. You also can't close map you have to force to close Minecraft. Even reloading the map, you will stuck in the catalog screen. Pressing Alt+F4 will break the whole game.

Greetings and thx for your help

### How to Reproduce?

Using MC 1.19.3 Forge 44.1.4

I've made the first launch with a tier 4 rocket with the jet suit. Was this my mistake. Do I need to make the first launch with a tier one rocket?

### Expected Behavior

Independently of the tiers of rockets and count of used mods, there should be a choise in the destination catalog when launching a rocket.

### Version

1.13.0

### Mod Loader Version

1.19.3 - 44.1.4

### Mod Loader

Forge

### Logs or additional context

	Mod List: 
		RoughlyEnoughProfessions-forge-1.19.3-1.2.0.jar   |Roughly Enough Professions    |roughlyenoughprofessions      |1.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		energizedpower-1.19.3-1.3.1.jar                   |Energized Power               |energizedpower                |1.19.3-1.3.1        |SIDED_SETU|Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.19.3-19.11.jar         |QuarryPlus                    |quarryplus                    |19.11               |SIDED_SETU|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.1+1.19.3.jar       |Player Animator               |playeranimator                |0.4.1+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		botarium-forge-1.19.3-2.0.1.jar                   |Botarium                      |botarium                      |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		EffectsLeft-1.19.3-0.1.2.jar                      |EffectsLeft                   |effectsleft                   |0.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		placeableblazerods-1.19.3-3.0.jar                 |Placeable Blaze Rods          |placeableblazerods            |3.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		HammerLib-1.19.3-19.4.47.jar                      |HammerLib                     |hammerlib                     |19.4.47             |SIDED_SETU|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		planttech2-0.02.58.jar                            |PlantTech 2                   |planttech2                    |0.02.58             |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_furniture-forge-1.19.3-1.0.0.jar        |Valhelsia Furniture           |valhelsia_furniture           |1.19.3-1.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		stonegrinder-1.0.5-1.19.3-forge.jar               |Stone Grinder                 |stonegrinder                  |1.0.5-1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		ImmersiveWeapons-1.19.3-1.19.1.jar                |Immersive Weapons             |immersiveweapons              |1.19.3-1.19.1       |SIDED_SETU|Manifest: NOSIGNATURE
		IronJetpacks-1.19.3-6.1.0.jar                     |Iron Jetpacks                 |ironjetpacks                  |6.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		CoffeeSpawner-1.19.3-11.0.0.jar                   |Coffee Spawner                |coffeespawner                 |1.19.3-11.0.0       |SIDED_SETU|Manifest: NOSIGNATURE
		ForgeEndertech-1.19.3-10.1.0.0-build.0001.jar     |ForgeEndertech                |forgeendertech                |10.1.0.0            |SIDED_SETU|Manifest: NOSIGNATURE
		everythingcopper-1.19.3-0.2.1.1.jar               |Everything is Copper          |everythingcopper              |1.19.3-0.2.1.1      |SIDED_SETU|Manifest: NOSIGNATURE
		softerhaybales-1.19.3-3.0.jar                     |Softer Hay Bales              |softerhaybales                |3.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		MoreBuckets-1.19.3-3.1.0.jar                      |More Buckets                  |morebuckets                   |3.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		macawsbridgesbop-1.19.3-1.0.jar                   |Macaw's Bridges - BOP         |macawsbridgesbop              |1.19.3-1.0          |SIDED_SETU|Manifest: NOSIGNATURE
		toolleveling-forge-1.19.3-1.4.4.jar               |Tool Leveling                 |toolleveling                  |1.19.3-1.4.4        |SIDED_SETU|Manifest: NOSIGNATURE
		MineTraps-1.19.3-(v.2.2.5).jar                    |MineTraps                     |minetraps                     |2.2.5               |SIDED_SETU|Manifest: NOSIGNATURE
		balm-forge-1.19.3-5.0.1.jar                       |Balm                          |balm                          |5.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		WaterStrainer-1.19.3-15.0.0.jar                   |Water Strainer                |waterstrainer                 |1.19.3-15.0.0       |SIDED_SETU|Manifest: NOSIGNATURE
		immersive_armors-1.5.2+1.19.3-forge.jar           |Immersive Armors              |immersive_armors              |1.5.2+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		cloth-config-9.0.94-forge.jar                     |Cloth Config v9 API           |cloth_config                  |9.0.94              |SIDED_SETU|Manifest: NOSIGNATURE
		stackrefill-1.19.3-4.0.jar                        |Stack Refill                  |stackrefill                   |4.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		structure_gel-1.19.3-2.8.0.jar                    |Structure Gel API             |structure_gel                 |2.8.0               |SIDED_SETU|Manifest: NOSIGNATURE
		handcrafted-forge-1.19.3-2.0.4.jar                |Handcrafted                   |handcrafted                   |2.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		ToolStats-Forge-1.19.3-13.0.1.jar                 |ToolStats                     |toolstats                     |13.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TexelsPaintings-forge-1.19.3-7.0.0.jar            |TexelsPaintings               |texelspaintings               |7.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.8-mc1.19.3forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.8               |SIDED_SETU|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.3-1.1.1.jar          |Resourcefulconfig             |resourcefulconfig             |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		ImprovableSkills-1.19.3-19.4.7.jar                |Improvable Skills             |improvableskills              |19.4.7              |SIDED_SETU|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ManyIdeasCore-1.19.3-1.4.0.jar                    |ManyIdeas Core                |manyideas_core                |1.4.0               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.19.3-5.1.2.0.jar                   |Curios API                    |curios                        |1.19.3-5.1.2.0      |SIDED_SETU|Manifest: NOSIGNATURE
		advancednetherite-1.14.6-1.19.3.jar               |Advanced Netherite            |advancednetherite             |1.14.6              |SIDED_SETU|Manifest: NOSIGNATURE
		TheAdditionsMod-1.19.3-1.1.jar                    |The Additions Mod             |theadditionsmod               |1.19.3-1.1          |SIDED_SETU|Manifest: NOSIGNATURE
		storageracks-1.19.3-1.1.5.jar                     |Storage Racks                 |storageracks                  |1.19.3-1.1.5        |SIDED_SETU|Manifest: NOSIGNATURE
		ninjascash-1.19.3-2.5.1.jar                       |Ninja's Cash                  |ninjascash                    |1.19.3-2.5.1        |SIDED_SETU|Manifest: NOSIGNATURE
		tombstone-8.3.0-1.19.3.jar                        |Corail Tombstone              |tombstone                     |8.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		dragon_enchants-1.0.2.jar                         |Dragon Enchants               |dragonenchants                |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		morechests-forge-1.19.3-1.0.2.jar                 |More Chests                   |more_chests                   |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Adorn-4.0.1+1.19.3-forge.jar                      |Adorn                         |adorn                         |4.0.1+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		woodenbucket-1.19.3-1.2.0.0.jar                   |Wooden Bucket                 |woodenbucket                  |1.19.3-1.2.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.6.6_mc1.19.3.jar              |ItemPhysic                    |itemphysic                    |1.6.6               |SIDED_SETU|Manifest: NOSIGNATURE
		the_bumblezone_forge-6.6.1+1.19.3.jar             |The Bumblezone                |the_bumblezone                |6.6.1+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		Enhanced-Farming-1.19.3-1.6.0.jar                 |Enhanced Farming              |enhancedfarming               |1.6.0               |SIDED_SETU|Manifest: NOSIGNATURE
		RuneCraft-1.19.3-(v.3.6.3).jar                    |RuneCraft                     |runecraft                     |3.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		MoreThanAPickaxe-1.19.3-0.1.7.jar                 |More Than A Pickaxe           |morethanapickaxe              |0.1.7               |SIDED_SETU|Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.19.3-14.0.1.jar             |DarkPaintings                 |darkpaintings                 |14.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		SurvivalPlus-Primer-1.19.3-0.1.0d.jar             |SurvivalPlus Primer           |survivalplus_primer           |0.1.0d              |SIDED_SETU|Manifest: NOSIGNATURE
		randombonemealflowers-1.19.3-4.0.jar              |Random Bone Meal Flowers      |randombonemealflowers         |4.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		SmartBrainLib-forge-1.19.3-1.7.3.jar              |SmartBrainLib                 |smartbrainlib                 |1.7.3               |SIDED_SETU|Manifest: NOSIGNATURE
		doubledoors_1.19.3-3.5.jar                        |Double Doors                  |doubledoors                   |3.5                 |SIDED_SETU|Manifest: NOSIGNATURE
		DisenchantmentEditTable-1.19.3-1.1.0.jar          |Disenchantment Edit Table     |editenchanting                |1.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		SurvivalPlus-Lightsabers-1.19.3-0.1.7.jar         |SurvivalPlus Lightsabers      |lightsaber                    |0.1.7               |SIDED_SETU|Manifest: NOSIGNATURE
		harvestwithease-1.19.3-5.0.0.0-forge.jar          |Harvest with ease             |harvestwithease               |5.0.0.0             |SIDED_SETU|Manifest: NOSIGNATURE
		Contact-Forge-1.19.3-2.0.1-Release.jar            |Contact                       |contact                       |2.0.1-Release       |SIDED_SETU|Manifest: NOSIGNATURE
		ctd-core-1.19.3-2.2.2b.jar                        |CTD Core                      |ctdcore                       |2.2.2b              |SIDED_SETU|Manifest: NOSIGNATURE
		sootychimneys-1.19.3-1.0.0.jar                    |Sooty Chimneys                |sootychimneys                 |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		TslatEffectsLib-forge-1.19.3-1.4.2.jar            |Tslat EffectsLib              |tslateffectslib               |1.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		brickfurnace-1.19.3-1.9.1.0.jar                   |Brick Furnace                 |brickfurnace                  |1.19.3-1.9.1.0      |SIDED_SETU|Manifest: NOSIGNATURE
		NaturesCompass-1.19.3-1.10.1-forge.jar            |Nature's Compass              |naturescompass                |1.19.3-1.10.1-forge |SIDED_SETU|Manifest: NOSIGNATURE
		AdHooks-1.19.3-9.1.0.0-build.0001.jar             |Advanced Hook Launchers       |adhooks                       |9.1.0.0             |SIDED_SETU|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19.3-12.0.1.jar      |Farming for Blockheads        |farmingforblockheads          |12.0.1              |SIDED_SETU|Manifest: NOSIGNATURE
		table_top_craft-1.19.3-4.0.1.jar                  |Table Top Craft               |table_top_craft               |1.19.3-4.0.1        |SIDED_SETU|Manifest: NOSIGNATURE
		ManyIdeasHalloween-1.19.3-1.0.0.jar               |ManyIdeas Halloween           |manyideas_halloween           |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		catalogue-1.7.0-1.19.3.jar                        |Catalogue                     |catalogue                     |1.7.0               |SIDED_SETU|Manifest: NOSIGNATURE
		ManyIdeasChristmas-1.19.3-1.0.0.jar               |ManyIdeas Christmas           |manyideas_christmas           |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		EdivadLib-1.19.3-1.3.0.jar                        |EdivadLib                     |edivadlib                     |1.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.19.3-44.1.4-universal.jar                 |Forge                         |forge                         |44.1.4              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		block_limit_fix-1.0.3-forge.jar                   |Block Limit Fix               |block_limit_fix               |1.0.3-forge         |SIDED_SETU|Manifest: NOSIGNATURE
		mo-glowstone-1.19.3-2.3.3b.jar                    |Mo' Glowstone                 |moglowstone                   |2.3.3b              |SIDED_SETU|Manifest: NOSIGNATURE
		mssw-forge-1.19.3-2.2.0.jar                       |More Slabs, Stairs, and Walls |more_slabs_stairs_and_walls   |2.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		theoneprobe-1.19.3-7.0.0.jar                      |The One Probe                 |theoneprobe                   |1.19.3-7.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		appliedenergistics2-forge-13.0.5-beta.jar         |Applied Energistics 2         |ae2                           |13.0.5-beta         |SIDED_SETU|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.3-2.1.0.137.jar           |TerraBlender                  |terrablender                  |2.1.0.137           |SIDED_SETU|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19.3-2.24.jar               |Mouse Tweaks                  |mousetweaks                   |2.24                |SIDED_SETU|Manifest: NOSIGNATURE
		bettercombat-forge-1.5.4+1.19.3.jar               |Better Combat                 |bettercombat                  |1.5.4+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		ava-1.19.3-2.3.0.jar                              |A.V.A - Alliance of Valiant Ar|ava                           |2.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		ceramicbucket-1.19.3-3.2.1.0.jar                  |Ceramic Bucket                |ceramicbucket                 |1.19.3-3.2.1.0      |SIDED_SETU|Manifest: NOSIGNATURE
		spectrelib-forge-0.12.1+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.1+1.19.2       |SIDED_SETU|Manifest: NOSIGNATURE
		domum_ornamentum-1.19.3-1.0.78-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.19.3-1.0.78-ALPHA |SIDED_SETU|Manifest: NOSIGNATURE
		pipez-1.19.3-1.0.3.jar                            |Pipez                         |pipez                         |1.19.3-1.0.3        |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentMachine-1.19.3-1.1.0-alpha+20221218-140|Enchantment Machine           |enchantmentmachine            |1.1.0-alpha+20221218|SIDED_SETU|Manifest: NOSIGNATURE
		ecologics-forge-1.19.3-2.1.12.jar                 |Ecologics                     |ecologics                     |2.1.12              |SIDED_SETU|Manifest: NOSIGNATURE
		[1.19.3]+SecurityCraft+v1.9.4-beta1.jar           |SecurityCraft                 |securitycraft                 |1.9.4-beta1         |SIDED_SETU|Manifest: NOSIGNATURE
		searchlight-1.19.3-forge-1.1.9.jar                |Searchlight                   |searchlight                   |1.1.9               |SIDED_SETU|Manifest: NOSIGNATURE
		wilescollection-1.19.3-forge-1.4.3.jar            |WilE's Collection             |wilescollection               |1.4.3               |SIDED_SETU|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		ManyIdeasDoors-1.19.3-1.2.2.jar                   |ManyIdeas Doors               |manyideas_doors               |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		structurize-1.19.3-1.0.477-ALPHA.jar              |Structurize                   |structurize                   |1.19.3-1.0.477-ALPHA|SIDED_SETU|Manifest: NOSIGNATURE
		mo-glowstone-lamps-1.19.3-1.3.1b.jar              |Mo' Glowstone Lamps           |moglowstonelamps              |1.3.1b              |SIDED_SETU|Manifest: NOSIGNATURE
		custom-crosshair-mod-v1.5.3-forge-mc1.19.3.jar    |Custom Crosshair Mod          |custom_crosshair_mod          |1.5.2-forge         |SIDED_SETU|Manifest: NOSIGNATURE
		PickleTweaks-1.19.3-7.1.0.jar                     |Pickle Tweaks                 |pickletweaks                  |7.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		MagicalTorches-1.19.3-2.0.2.jar                   |Magical Torches               |magical_torches               |2.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Legendary+Item+v4.1.jar                           |Legendary Item                |legendarium                   |4.1                 |SIDED_SETU|Manifest: NOSIGNATURE
		Aquaculture-1.19.3-2.4.11.jar                     |Aquaculture 2                 |aquaculture                   |1.19.3-2.4.11       |SIDED_SETU|Manifest: NOSIGNATURE
		Exotelcraft-1.19.3-4.0.0-BETA-4.jar               |Exotelcraft                   |better_minecraft              |4.0.0 BETA          |SIDED_SETU|Manifest: NOSIGNATURE
		UncraftingTable-forge-1.1.7.jar                   |Uncrafting Table              |uncraftingtable76             |1.1.7               |SIDED_SETU|Manifest: NOSIGNATURE
		xptome-1.19.3-2.1.7.jar                           |XP Tome                       |xpbook                        |2.1.7               |SIDED_SETU|Manifest: NOSIGNATURE
		ad_astra-forge-1.19.3-1.13.0.jar                  |Ad Astra!                     |ad_astra                      |1.13.0              |SIDED_SETU|Manifest: NOSIGNATURE
		nyliumnasturtium-1.19.3-1.0.jar                   |Nylium Nasturtium             |nyliumnasturtium              |1.19.3-1.0          |SIDED_SETU|Manifest: NOSIGNATURE
		blue_skies-1.19.3-1.3.22.jar                      |Blue Skies                    |blue_skies                    |1.3.22              |SIDED_SETU|Manifest: NOSIGNATURE
		netherportalfix-forge-1.19.3-11.0.0.jar           |NetherPortalFix               |netherportalfix               |11.0.0              |SIDED_SETU|Manifest: NOSIGNATURE
		fpplus-1.0.1-1.19.3.jar                           |Flower Pots Plus              |fpplus                        |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		blazegear-1.19.3-1.3.4.jar                        |Blaze Gear                    |blazegear                     |1.19.3-1.3.4        |SIDED_SETU|Manifest: NOSIGNATURE
		extraaoainfo-1.19.2-1.19.3-1.0.1.jar              |Extra AoA Info                |aoainfo                       |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		AoA3-1.19.3-3.6.20.jar                            |Advent of Ascension           |aoa3                          |3.6.20              |SIDED_SETU|Manifest: NOSIGNATURE
		ExtendedCrafting-1.19.3-5.2.0.jar                 |Extended Crafting             |extendedcrafting              |5.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		scalar_utils-1.19.3-5.0.12.jar                    |Scalar Utils 5: Definitive Edi|scalar_utils                  |1.19.3-5.0.12       |SIDED_SETU|Manifest: NOSIGNATURE
		advancements_tracker_1.19.3-5.0.0.jar             |Advancements Tracker          |advancements_tracker          |5.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		dynamiclights-1.19.3.1.jar                        |Dynamic Lights                |dynamiclights                 |1.19.3.1            |SIDED_SETU|Manifest: NOSIGNATURE
		excavatedvariants-forge-1.19.3-2.0.1.jar          |Excavated Variants            |excavated_variants            |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.7_Forge_1.19.3.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.7              |SIDED_SETU|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.19.3-14.0.1.jar      |CookingForBlockheads          |cookingforblockheads          |14.0.1              |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-2.2.3-1.19.3.jar                          |Citadel                       |citadel                       |2.2.3               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.22.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.0              |SIDED_SETU|Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-10.0.45.jar        |REI Plugin Compatibilities    |rei_plugin_compatibilities    |10.0.45             |SIDED_SETU|Manifest: NOSIGNATURE
		fire_extinguisher_1.19.3-5.0.0.jar                |Fire Extinguisher             |fire_extinguisher             |5.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		spawnermod-1.19.3-1.9.2+Forge.jar                 |Enhanced Mob Spawners         |spawnermod                    |1.9.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.3-17.0.3.jar                 |Bookshelf                     |bookshelf                     |17.0.3              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		generatorgalore-1.19.3-0.1.0.4.jar                |Generator Galore              |generatorgalore               |1.19.3-0.1.0.4      |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-bridges-2.0.6-mc1.19.3forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |SIDED_SETU|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.15_mc1.19.3.jar          |Ambient Sounds                |ambientsounds                 |5.2.15              |SIDED_SETU|Manifest: NOSIGNATURE
		defaultresources-forge-1.19.3-1.0.1.jar           |Default Resources             |defaultresources              |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		mining_dimension-1.19.3-1.0.2.jar                 |Mining World                  |mining_dimension              |1.19.3-1.0.2        |SIDED_SETU|Manifest: NOSIGNATURE
		simplylight-1.19.3-1.4.5-build.46.jar             |Simply Light                  |simplylight                   |1.19.3-1.4.5-build.4|SIDED_SETU|Manifest: NOSIGNATURE
		xercamod-1.19.3-1.0.1.jar                         |Xerca Mod                     |xercamod                      |1.19.3-1.0.1        |SIDED_SETU|Manifest: NOSIGNATURE
		simplybackpacks-1.19.3-2.1.5-build.48.jar         |Simply Backpacks              |simplybackpacks               |1.19.3-2.1.5-build.4|SIDED_SETU|Manifest: NOSIGNATURE
		SolarFluxReborn-1.19.3-19.4.7.jar                 |Solar Flux Reborn             |solarflux                     |19.4.7              |SIDED_SETU|Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		hole_filler_mod-1.2.7-mc_1.19.3-forge.jar         |Hole Filler Mod               |hole_filler_mod               |1.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
		blockui-1.19.3-0.0.66-ALPHA.jar                   |UI Library Mod                |blockui                       |1.19.3-0.0.66-ALPHA |SIDED_SETU|Manifest: NOSIGNATURE
		multipiston-1.19.3-1.2.22-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.19.3-1.2.22-ALPHA |SIDED_SETU|Manifest: NOSIGNATURE
		collective-1.19.3-6.18.jar                        |Collective                    |collective                    |6.18                |SIDED_SETU|Manifest: NOSIGNATURE
		SewingKit-1.19.3-1.7.1.jar                        |Sewing Kit                    |sewingkit                     |1.7.1               |SIDED_SETU|Manifest: NOSIGNATURE
		camera-1.19.3-1.0.3.jar                           |Camera Mod                    |camera                        |1.19.3-1.0.3        |SIDED_SETU|Manifest: NOSIGNATURE
		simplehats-forge-1.19.3-0.1.6.jar                 |SimpleHats                    |simplehats                    |1.19.3-0.1.6        |SIDED_SETU|Manifest: NOSIGNATURE
		SurvivalPlus-1.19.3-0.1.7.jar                     |SurvivalPlus                  |survivalplus                  |0.1.7               |ERROR     |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.3-17.2.0.496.jar               |Biomes O' Plenty              |biomesoplenty                 |17.2.0.496          |SIDED_SETU|Manifest: NOSIGNATURE
		xercapaint-1.19.3-1.0.0.jar                       |Joy of Painting               |xercapaint                    |1.19.3-1.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		OpenBlocksElevator-1.19.3-1.8.10.jar              |Elevator Mod                  |elevatorid                    |1.19.3-1.8.10       |SIDED_SETU|Manifest: NOSIGNATURE
		MysticalCustomization-1.19.3-4.1.0.jar            |Mystical Customization        |mysticalcustomization         |4.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		expandedstorage-9.0.0-alpha.2+1.19.3-forge.jar    |Expanded Storage              |expandedstorage               |9.0.0-alpha.2       |SIDED_SETU|Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.3-1.2.2.jar             |Resourceful Lib               |resourcefullib                |1.2.2               |SIDED_SETU|Manifest: NOSIGNATURE
		BetterFurnaces-Forge-1.19.3-0.1.0.jar             |BetterFurnaces Reforged       |betterfurnacesreforged        |1.19.3-0.1.0        |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-7.0.65-forge.jar                     |Architectury                  |architectury                  |7.0.65              |SIDED_SETU|Manifest: NOSIGNATURE
		javd-forge-4.1.1-build.4+mc1.19.3.jar             |Just Another Void Dimension   |javd                          |4.1.1-build.4+mc1.19|SIDED_SETU|Manifest: NOSIGNATURE
		BuildingWands_mc1.19.3-2.6.4_release-forge.jar    |Building Wands                |wands                         |2.6.4_release       |SIDED_SETU|Manifest: NOSIGNATURE
		markdown_manual-MC1.19.3-forge-1.2.3+ff62d5c.jar  |Markdown Manual               |markdown_manual               |1.2.3+ff62d5c       |SIDED_SETU|Manifest: NOSIGNATURE
		tis3d-MC1.19.3-forge-1.7.2+7851f43.jar            |TIS-3D                        |tis3d                         |1.7.2+7851f43       |SIDED_SETU|Manifest: NOSIGNATURE
		cc-tweaked-1.19.3-forge-1.102.1.jar               |CC: Tweaked                   |computercraft                 |1.102.1             |SIDED_SETU|Manifest: NOSIGNATURE
		light-overlay-7.0.2-forge.jar                     |Light Overlay                 |lightoverlay                  |7.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		infinitetrading-1.19.3-4.0.jar                    |Infinite Trading              |infinitetrading               |4.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		TofuCraftReload-1.19.3-3.2.0.0.jar                |TofuCraftReload               |tofucraft                     |1.19.3-3.2.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
		MCDoom-Forge-1.19.3-4.3.4.jar                     |Doom Mod                      |doom                          |4.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.19.3-4.0.3.jar                   |GeckoLib 4                    |geckolib                      |4.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		magitekmechs-forge-MC1.19.3-1.0.15.jar            |Magitek Mechs                 |mtmechs                       |1.0.15              |SIDED_SETU|Manifest: NOSIGNATURE
		Cucumber-1.19.3-6.1.0.jar                         |Cucumber Library              |cucumber                      |6.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		redstonepen-1.19.3-forge-1.3.20.jar               |Redstone Pen                  |redstonepen                   |1.3.20              |SIDED_SETU|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		metalbarrels-1.19.3-5.1.jar                       |Metal Barrels                 |metalbarrels                  |1.19.3-5.1          |SIDED_SETU|Manifest: NOSIGNATURE
		mcskyblock-3.2.5.jar                              |MC Skyblock                   |mcskyblock                    |3.2.5               |SIDED_SETU|Manifest: NOSIGNATURE
		waystones-forge-1.19.3-12.0.1.jar                 |Waystones                     |waystones                     |12.0.1              |SIDED_SETU|Manifest: NOSIGNATURE
		MerchantMarkers-1.19.3-forge-1.3.0.jar            |Merchant Markers              |merchantmarkers               |1.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		AgeOfWeapons-Reforged-1.19.3-(v.0.7.4).jar        |Age of Weapons - Reforged     |ageofweapons                  |0.7.4               |SIDED_SETU|Manifest: NOSIGNATURE
		SilveroakOutpost-Forge-1.19.3-2.0.3-Release.jar   |Silveroak Outpost             |silveroakoutpost              |2.0.3-Release       |SIDED_SETU|Manifest: NOSIGNATURE
		mcpitanlibarch-1.3.1-1.19.3-forge.jar             |MCPitanLibarch                |mcpitanlibarch                |1.3.1-1.19.3-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		comforts-forge-6.1.0+1.19.3.jar                   |Comforts                      |comforts                      |6.1.0+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		Tumbleweed-forge-1.19.3-0.5.2.jar                 |Tumbleweed                    |tumbleweed                    |0.5.2               |SIDED_SETU|Manifest: NOSIGNATURE
		configured-2.0.2-1.19.3.jar                       |Configured                    |configured                    |2.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		MTR-forge-1.19.3-3.1.13-hotfix-1.jar              |Minecraft Transit Railway     |mtr                           |1.19.3-3.1.13-hotfix|SIDED_SETU|Manifest: NOSIGNATURE
		MTR-LU-Addon-forge-1.19.3-3.2.0-1.9.jar           |MTR London Underground Addon  |londonunderground             |1.19.3-3.2.0-1.9    |SIDED_SETU|Manifest: NOSIGNATURE
		MTR-MSD-Addon-forge-1.19.3-3.2.0-1.1-hotfix-1.jar |MTR Station Decoration Addon  |msd                           |1.19.3-3.2.0-1.1-hot|SIDED_SETU|Manifest: NOSIGNATURE
		ExplorersCompass-1.19.3-1.3.0-forge.jar           |Explorer's Compass            |explorerscompass              |1.19.3-1.3.0-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		drg_flares-1.19.3-forge-1.2.6.jar                 |DRG Flares                    |drg_flares                    |1.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
		RaysDongles-6.16+-+1.19.3.jar                     |Ray's Dongles                 |raysdongles                   |6.16                |SIDED_SETU|Manifest: NOSIGNATURE
		FluidSystem-1.19.3-3.3.0.jar                      |FluidSystem                   |fluidsystem                   |3.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		potionring-1.19.3-1.0.jar                         |Potion Rings - REFORGED       |potionring                    |1.19.3-1.0          |SIDED_SETU|Manifest: NOSIGNATURE
		TC-Redstone-1.19.3-3.1.2.jar                      |TC Redstone                   |gircredstone                  |3.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		tardim-1.1.3+-+1.19.3.jar                         |TARDIM                        |tardim                        |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		MysticalAgriculture-1.19.3-6.1.0.jar              |Mystical Agriculture          |mysticalagriculture           |6.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		MysticalAgradditions-1.19.3-6.1.0.jar             |Mystical Agradditions         |mysticalagradditions          |6.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		matc-1.4.0.jar                                    |Mystical Agriculture Tiered Cr|matc                          |1.4.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Trashed-1.19.3-1.1.8.jar                          |Trashed                       |trashed                       |1.1.8               |SIDED_SETU|Manifest: NOSIGNATURE
		FactoryAPI-Forge-1.19.3-0.1.3.jar                 |Factory API                   |factory_api                   |1.19.3-0.1.3        |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.3-14.0.6.jar   |EnchantmentDescriptions       |enchdesc                      |14.0.6              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		dynamicassetgenerator-forge-1.19.3-3.0.1.jar      |Dynamic Asset Generator       |dynamic_asset_generator       |3.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		bettercreeper-1.19.3_1.2.2.jar                    |Bettercreeper                 |bettercreeper                 |1.19.3 - 1.2.2      |SIDED_SETU|Manifest: NOSIGNATURE
		Journey-Into-The-Light-1.19.3-2.0.0.0.jar         |Journey Into the Light        |jitl                          |1.19.3-2.0.0.0      |SIDED_SETU|Manifest: NOSIGNATURE
		(forge+1.19.3)+regions_unexplored+r-193.1.15.jar  |Regions Unexplored            |regions_unexplored            |193.1.15            |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.3_mc1.19.3.jar            |CreativeCore                  |creativecore                  |2.9.3               |SIDED_SETU|Manifest: NOSIGNATURE
		infinitybuttons-1.19.3-3.1.0.jar                  |Infinity Buttons              |infinitybuttons               |1.19.3-3.1.0        |SIDED_SETU|Manifest: NOSIGNATURE
		sculktransporting-1.19.3-1.1.1.jar                |Sculk Transporting            |sculktransporting             |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		RecipesLibrary-1.19.3-2.0.1.jar                   |Recipes Library               |recipes_lib                   |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		RoughlyEnoughItems-10.0.581.jar                   |Roughly Enough Items (REI)    |roughlyenoughitems            |10.0.581            |SIDED_SETU|Manifest: NOSIGNATURE
		LargeFluidTank-19.9.jar                           |FluidTank                     |fluidtank                     |19.9                |SIDED_SETU|Manifest: NOSIGNATURE
		SelectablePainting-1.19.3-2.0.2.jar               |Selectable Painting           |selectable_painting           |2.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Iceberg-1.19.3-forge-1.1.2.jar                    |Iceberg                       |iceberg                       |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		bucketlib-1.19.3-1.1.0.1.jar                      |BucketLib                     |bucketlib                     |1.19.3-1.1.0.1      |SIDED_SETU|Manifest: NOSIGNATURE
		immersive_paintings-0.4.4+1.19.3-forge.jar        |Immersive Paintings           |immersive_paintings           |0.4.4+1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		zergatul.freecam-1.4.1-forge-1.19.3.jar           |FreeCam by Zergatul           |freecam                       |1.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		armourersworkshop-forge-1.19.3-2.0.0-beta.8.jar   |Armourer's Workshop           |armourers_workshop            |2.0.0-beta.8        |SIDED_SETU|Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a
		mvs-3.1.7-1.19.3.jar                              |Moog's Voyager Structures     |mvs                           |3.1.7-1.19.3        |SIDED_SETU|Manifest: NOSIGNATURE
		solidblocks-1.2.jar                               |Solid Blocks                  |solidblocks                   |1.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		modular-routers-1.19.3-11.0.0-5.jar               |Modular Routers               |modularrouters                |11.0.0-5            |SIDED_SETU|Manifest: NOSIGNATURE
		BetterF3-5.1.0-Forge-1.19.3.jar                   |BetterF3                      |betterf3                      |5.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		pgwbandedtorches-1.19.3-1.0.20230105a.jar         |PixelGameWizard's Banded Torch|pgwbandedtorches              |1.19.3-1.0.20230105a|SIDED_SETU|Manifest: NOSIGNATURE
		SolarGeneration-1.19.3-5.3.0.jar                  |Solar Generation              |solargeneration               |5.3.0               |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_core-forge-1.19.3-0.5.0.jar             |Valhelsia Core                |valhelsia_core                |1.19.3-0.5.0        |SIDED_SETU|Manifest: NOSIGNATURE
		xtonesreworked-1.0.1-1.19.3.jar                   |Xtones Reworked               |xtonesreworked                |1.0.0-1.19.2-43.1.47|SIDED_SETU|Manifest: NOSIGNATURE
		ExtraGems-1.19.3-(v.2.1.3).jar                    |ExtraGems                     |extragems                     |2.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
		PresenceFootsteps-1.19.3-1.7.1-forge.jar          |Presence Footsteps (Forge)    |presencefootsteps             |1.19.3-1.7.1        |SIDED_SETU|Manifest: NOSIGNATURE

**Comment by AlexNijjar** [comment]
try in the latest 1.19.3 version

**Comment by SubSonicEr** [comment]
Thx for investing time to make a fix :)

**Comment by SubSonicEr** [comment]
Ad Adstra has failed to load in the newest version 1.13.1 for MC 1.19.3 Forge with Forge 44.1.5 with the error "java.lang.reflect.InvocationTargetException:null"

Is this error note okay or do you need the full crash log?

EDIT: It seems to be, that the newest library version "botarium-forge-1.19.3-2.0.4.jar" is causing this issue. With "botarium-forge-1.19.3-2.0.1.jar" the newest version of "Ad Astra" is loading correctly.

EDIT: The issue of the former version is persisting in the newest version. I'm using a 4k resolution in MC. Could this be the cause of the issue?

**Comment by AlexNijjar** [comment]
yeah send that crash log.

as for the main issue here, it happens only on forge and was fixed in 1.19.2, don't know why it's breaking for 1.19.3. are you on a single player world or a dedicated server?

**Comment by SubSonicEr** [comment]
Hey there,

the newest version ad_astra-forge-1.19.3-1.13.2 is now working with the newest version botarium-forge-1.19.3-2.0.4.jar. But the empty catalog issue is still persisting. I'm playing my mod collection in a single player map. Additionally I'd like to tell you, that I'm using the following dependencies for "Ad Astra":

Botarium
Roughly Enough Items (Optional but one of my first used mods)
Resourceful Lib
Resourceful Config

I don't think, that JEI is needed for "Ad Astra" to work correctly, especially REI is replacing JEI. I'd like to use Patchouli but for now there is no version for MC 1.19.3 Forge. Could the missing "Patchouli" dependency cause my issue?

Greetings

**Comment by SubSonicEr** [comment]
Could you recommend me steps how to test the "Ad Astra" rocket travel system correctly? Maybe it's the false way to use the creative mode and simply add a launch pad and a full filled rocket tier 4.

Thx for the nice contact for now

Greetings

**Comment by AlexNijjar** [comment]
the main issue here fixed in 1.13.3, I tested on a forge dedicated server and it worked.

- JEI is not needed to work correctly? it's an optional dependency.

- For the most simple test, you can just open the gui with the /planetgui command. For testing the rocket travel, the thing you said works best.

**Comment by SubSonicEr** [comment]
Hey there,

thx for fixing the issue in MC 1.19.3 Forge and your help. I've tested the new version and the catalog is working fine.

Greetings and thx for the nice contact
